# Generated by Django 5.0.6 on 2024-06-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=256)),
                ('customer_name', models.CharField(max_length=256)),
                ('customer_address', models.CharField(max_length=256)),
                ('total_price', models.IntegerField()),
                ('order_status', models.CharField(choices=[('ORDERED', 'Ordered'), ('Failed', 'Failed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=80)),
                ('Payment_method', models.CharField(choices=[('Failed', 'Failed'), ('COD', 'COD'), ('Debit/Credit card', 'Debit/Credit card'), ('Net banking', 'Net Banking')], max_length=80)),
                ('Payment_status', models.CharField(choices=[('paid', 'Paid'), ('Not paid', 'Not paid'), ('Failed', 'Failed')], max_length=80)),
                ('shipment_awb', models.CharField(blank=True, default='', max_length=256)),
                ('logistic_partner', models.CharField(blank=True, choices=[('fed-ex', 'Fed-ex'), ('e-kart', 'e-kart')], max_length=80)),
                ('shipment_status', models.CharField(choices=[('Preparing', 'preparing'), ('SHIPPED', 'Shipped'), ('IN-TRANSIT', 'In-Transit'), ('DELIVERED', 'Delivered')], default='Preparing', max_length=80)),
            ],
        ),
    ]
