# Generated by Django 5.0.6 on 2024-07-13 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_user_customer_customer_and_more'),
        ('order', '0001_initial'),
        ('product', '0002_unit_rename_price_product_discount_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=50)),
                ('coupon_amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='shippingcharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_charge', models.IntegerField(default=0)),
                ('minimum_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Debit/Credit card', 'Debit/Credit card'), ('Net banking', 'Net banking')], default='COD', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('Failed', 'Failed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ORDERED', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('SHIPPED', 'Shipped'), ('IN-TRANSIT', 'In-Transit'), ('DELIVERED', 'Delivered')], default='Preparing', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Ordereditem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='shippingaddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
