# Generated by Django 5.0.6 on 2024-07-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_coupon_shippingcharge_remove_order_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
