# Generated by Django 5.0.6 on 2024-06-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_item'),
        ('product', '0004_alter_product_disount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('Failed', 'Failed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ORDERED', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('SHIPPED', 'Shipped'), ('IN-TRANSIT', 'In-Transit'), ('DELIVERED', 'Delivered')], default='Preparing', max_length=80),
        ),
        migrations.CreateModel(
            name='Ordereditem',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.ordereditem'),
            preserve_default=False,
        ),
    ]
