# Generated by Django 5.0.6 on 2024-07-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='message',
            new_name='discount_coupon',
        ),
    ]
