# Generated by Django 5.0.6 on 2024-07-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_customer_name_remove_cart_date_added_and_more'),
        ('order', '0004_rename_message_order_discount_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cartitem'),
        ),
    ]
