# Generated by Django 5.0.6 on 2024-06-29 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_product_delete_ordereditem'),
        ('product', '0004_alter_product_disount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordereditem',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
    ]
