# Generated by Django 5.0.6 on 2024-07-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordereditem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.CharField(max_length=256),
        ),
    ]
