# Generated by Django 5.0.6 on 2024-06-29 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='order.ordereditem'),
            preserve_default=False,
        ),
    ]
