# Generated by Django 5.0.6 on 2024-06-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='order_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),
    ]
