# Generated by Django 5.0.6 on 2024-07-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
    ]
