# Generated by Django 5.0.6 on 2024-07-18 09:47

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_shippingaddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2024, 7, 18, 13, 47, 8, 212708)),
            preserve_default=False,
        ),
    ]
