# Generated by Django 5.0.6 on 2024-06-29 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_order_id_ordereditem_id_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
