# Generated by Django 5.0.6 on 2024-06-30 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_address_address'),
        ('order', '0011_remove_order_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.address'),
            preserve_default=False,
        ),
    ]
