# Generated by Django 5.0.6 on 2024-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='shippingcharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_charge', models.CharField(max_length=24)),
                ('minimum_amount', models.CharField(max_length=24)),
            ],
        ),
    ]
