# Generated by Django 5.0.6 on 2024-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_shippingcharge_minimum_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=50)),
            ],
        ),
    ]
