# Generated by Django 5.0.6 on 2024-07-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_discount_amount_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_amount',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
