# Generated by Django 5.0.6 on 2024-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_coupon_coupon_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_amount',
            field=models.CharField(max_length=10),
        ),
    ]
