# Generated by Django 5.0.6 on 2024-06-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=256)),
                ('max_quantity', models.CharField(max_length=256)),
                ('thumbnail', models.CharField(max_length=256)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
