# Generated by Django 5.0.6 on 2024-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_unit_alter_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='discount_price',
        ),
        migrations.AddField(
            model_name='product',
            name='disount_percentage',
            field=models.IntegerField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='orginal_price',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
