# Generated by Django 5.0.6 on 2024-06-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_price_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disount_percentage',
            field=models.IntegerField(),
        ),
    ]
