# Generated by Django 5.0.6 on 2024-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_disount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=400, upload_to='product/'),
        ),
    ]
