# Generated by Django 5.0.6 on 2024-06-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='f_name',
            field=models.CharField(default=2, max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
    ]
