# Generated by Django 5.0.6 on 2024-06-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_name_customer_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='l_name',
            field=models.CharField(default=32, max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default=3, max_length=80, verbose_name='mobile number'),
            preserve_default=False,
        ),
    ]
